### ISSUE TITLE
Decide on breakfast item

### ISSUE THREAD

**Issue by myronhc** [IntroToCode/CodeMates7_Spring23#1]
## 💬 Discussion topic

What should our breakfast recipe be for?

## ❗ Potential issues

Overly complicated recipe; disagreement between team members

## 👥 People to consult

The entire team

## 📃 Details

I propose going with something with relatively simple ingredients and a few steps. How about eggs or waffles?

**Comment by jklee-bear** [comment]
Eggs and waffles (+ maple syrup) sounds good!

**Comment by edubattagin** [comment]
I'm ok with it!

**Comment by Tiffany-Shumate** [comment]
works for me too
