### ISSUE TITLE
Decide on dinner recipe

### ISSUE THREAD

**Issue by spg222** [IntroToCode/CodeMates7_Spring23#2]
Decide on a dinner recipe

**Comment by myronhc** [comment]
I'm feeling like I need a detox and want a healthy meal. How about a salad? What is everyone's favourite go-to salad>

**Comment by spg222** [comment]
I love olives and pickled things!!!!!

**Comment by jklee-bear** [comment]
Let's start by eliminating things we don't want for dinner?

**Comment by myronhc** [comment]
Here's the criteria I suggested for deciding what dinner to make:
Time needed: under 30 minutes
number of ingredients: no more than 5 ingredients
Equipment needed: no more than 5 pieces of equipment
Steps for prep: no more than 7 steps
