### ISSUE TITLE
Consider dietary restrictions

### ISSUE THREAD

**Issue by jklee-bear** [IntroToCode/CodeMates7_Spring23#3]
## 💬 Discussion topic

Consider every teammates dietary restrictions before selecting breakfast/dinner recipe

## ❗ Potential issues

A teammate being upset about a menu that doesn't consider one's dietary restriction

## 👥 People to consult

Everyone in the team

## 📃 Details

Please share your dietary restrictions. FYI, I can't eat cucumber

**Comment by myronhc** [comment]
Noted that the recipe cannot contain cucumbers. I do not have dietary restrictions. Thanks for asking!

**Comment by spg222** [comment]
I prefer pescatarian diet.

**Comment by edubattagin** [comment]
I don't have any dietary restrictions =)
