### ISSUE TITLE
Recipe Planning 

### ISSUE THREAD

**Issue by spg222** [IntroToCode/CodeMates7_Spring23#4]
@myronhc Decide on the number of servings for breakfast and dinner item
@Tiffany-Shumate Decide on time to prepare for breakfast and dinner items
@jklee-bear Decide on ingredients for both breakfast and dinner items with our dietary requirements considered
@spg222 Decide on equipment needed
@edubattagin Decide on steps for preparation for breakfast and dinner item

**Comment by jklee-bear** [comment]
aye aye captain!

**Comment by myronhc** [comment]
on it!

**Comment by spg222** [comment]
I am going to split the above up into separate issues! Let's have one pull request per issue. 

@Tiffany-Shumate already raised a pull  request for her issue [here. ](https://github.com/IntroToCode/CodeMates7_Spring23/pull/6). 

It needs one more approval! I will it keep it open.
