### ISSUE TITLE
Decide on ingredients for both breakfast and dinner items with our dietary requirements considered 

### ISSUE THREAD

**Issue by spg222** [IntroToCode/CodeMates7_Spring23#9]
## 💬 Discussion topic

Text

## ❗ Potential issues

Text

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by jklee-bear** [comment]
Ingredients for breakfast - Eggs, Waffles, Maple Syrup
Ingredients for dinner - Parmesan Cheese, Caesar Salad Dressing, Olives, Crouton, Lettuce

**Comment by Tiffany-Shumate** [comment]
Done!
